# Generated by Django 3.0.8 on 2022-04-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('mobile_no', models.IntegerField()),
                ('address', models.CharField(max_length=225)),
                ('DC_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='showroom_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bike', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Color')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.variant')),
            ],
        ),
        migrations.CreateModel(
            name='showroom_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_qty', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xcxcsxcs', to='stores.Color')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsx', to='stores.distributor')),
                ('showroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfdscf', to='stores.showroom')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xcxcsxcs', to='stores.variant')),
            ],
        ),
        migrations.CreateModel(
            name='showroom_outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('battery_no', models.CharField(max_length=550)),
                ('battery_type', models.CharField(choices=[('lithium', 'Lithium'), ('gel', 'Gel')], default='lithium', max_length=50)),
                ('bike_qty', models.IntegerField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='showroom.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='showroom_inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_outward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdfdfsdx', to='transactions.outward')),
                ('distributor_outward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor_outward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='showroom_bike_number_outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bike_number', unique=True)),
                ('outward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom_outward')),
            ],
        ),
    ]
