# Generated by Django 3.0.8 on 2022-04-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom_outward',
            name='customer_service_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
