# Generated by Django 3.0.8 on 2022-04-05 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showroom', '0002_showroom_outward_customer_service_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom_stock',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
