# Generated by Django 3.0.8 on 2022-04-07 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20220405_1720'),
        ('showroom', '0003_showroom_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom_request',
            name='bike_qty',
        ),
        migrations.RemoveField(
            model_name='showroom_request',
            name='color',
        ),
        migrations.RemoveField(
            model_name='showroom_request',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='showroom_request',
            name='variant',
        ),
        migrations.AddField(
            model_name='showroom_request',
            name='pr_pdf',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='showroom_req',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_qty', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xcxcsxcs', to='stores.Color')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsx', to='stores.distributor')),
                ('showroom_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom_request')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xcxcsxcs', to='stores.variant')),
            ],
        ),
    ]
