# Generated by Django 3.0.8 on 2022-04-07 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20220405_1720'),
        ('showroom', '0004_auto_20220408_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showroom_req',
            name='distributor',
        ),
        migrations.AddField(
            model_name='showroom_request',
            name='distributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsx', to='stores.distributor'),
        ),
    ]
