# Generated by Django 3.0.8 on 2022-04-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0006_distributor_payment_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='distributor_payment_details',
            new_name='showroom_payment_details',
        ),
    ]
