# Generated by Django 3.0.8 on 2022-06-21 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_bike_number_outward_return_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('showroom', '0007_auto_20220408_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='showroom_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bike_qty', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='distributor_bike_number_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsdwwwd', to='transactions.bike_number', unique=True)),
                ('inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='showroom.showroom_inward')),
                ('showroom_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdwfefsd', to='showroom.showroom_return')),
            ],
        ),
    ]
