# Generated by Django 3.0.8 on 2022-06-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_bike_number_outward_return_status'),
        ('showroom', '0008_distributor_bike_number_return_showroom_return'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='distributor_bike_number_return',
            new_name='showroom_bike_number_return',
        ),
    ]
