# Generated by Django 3.0.8 on 2022-06-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_bike_number_outward_return_status'),
        ('distributor', '0022_distributor_bike_number_return_company_outward'),
        ('showroom', '0011_showroom_bike_number_return_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='showroom_bike_number_return',
            name='outward_company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.outward'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showroom_bike_number_return',
            name='outward_distributor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor_outward'),
            preserve_default=False,
        ),
    ]
