# Generated by Django 3.0.8 on 2022-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0015_auto_20220704_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom_outward',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='showroom_req',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
