# Generated by Django 3.0.8 on 2022-02-06 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220206_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dealer',
        ),
    ]
