# Generated by Django 3.0.8 on 2022-04-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='distributor_stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bike', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Color')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.variant')),
            ],
        ),
        migrations.CreateModel(
            name='distributor_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_qty', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dcdxcdvfes', to='stores.Color')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dfdscf', to='stores.distributor')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdssfsfdf', to='stores.variant')),
            ],
        ),
        migrations.CreateModel(
            name='distributor_outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bike_qty', models.IntegerField()),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.showroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='distributor_inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_outward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.outward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='distributor_bike_number_outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bike_number', unique=True)),
                ('outward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor_outward')),
            ],
        ),
    ]
