# Generated by Django 3.0.8 on 2022-04-06 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0004_auto_20220406_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='distributor_pr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_pdf', models.FileField(null=True, upload_to='static/distributor/pr')),
                ('distributor_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor_request')),
            ],
        ),
    ]
