# Generated by Django 3.0.8 on 2022-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0005_distributor_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_request',
            name='pr_pdf',
            field=models.FileField(null=True, upload_to='static/distributor/pr'),
        ),
        migrations.DeleteModel(
            name='distributor_pr',
        ),
    ]
