# Generated by Django 3.0.8 on 2022-04-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0006_auto_20220406_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor_request',
            name='pr_pdf',
            field=models.CharField(default='sdsd', max_length=500),
            preserve_default=False,
        ),
    ]
