# Generated by Django 3.0.8 on 2022-05-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0008_distributor_payment_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor_bike_number_outward',
            name='outward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='distributor.distributor_outward'),
        ),
    ]
