# Generated by Django 3.0.8 on 2022-06-19 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_bike_number_outward_price'),
        ('distributor', '0009_auto_20220525_0148'),
    ]

    operations = [
        migrations.CreateModel(
            name='distributor_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bike_qty', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='distributor_bike_number_return',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bike_number', unique=True)),
                ('distributor_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='distributor.distributor_return')),
            ],
        ),
    ]
