# Generated by Django 3.0.8 on 2022-06-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0010_distributor_bike_number_return_distributor_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_bike_number_return',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
