# Generated by Django 3.0.8 on 2022-06-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0011_distributor_bike_number_return_return_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor_bike_number_return',
            name='return_status',
        ),
        migrations.AddField(
            model_name='distributor_bike_number_outward',
            name='return_status',
            field=models.BooleanField(default=False),
        ),
    ]
