# Generated by Django 3.0.8 on 2022-06-19 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0012_auto_20220620_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor_bike_number_outward',
            name='return_status',
        ),
    ]
