# Generated by Django 3.0.8 on 2022-06-19 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20220620_0223'),
        ('distributor', '0014_auto_20220620_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor_bike_number_return',
            name='bike_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bike_number'),
        ),
    ]
