# Generated by Django 3.0.8 on 2022-06-20 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0016_auto_20220620_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_return',
            name='inward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='distributor.distributor_inward'),
            preserve_default=False,
        ),
    ]
