# Generated by Django 3.0.8 on 2022-06-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0019_auto_20220621_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_bike_number_return',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
