# Generated by Django 3.0.8 on 2022-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0020_distributor_bike_number_return_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_bike_number_outward',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
