# Generated by Django 3.0.8 on 2022-06-24 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_bike_number_outward_return_status'),
        ('distributor', '0021_distributor_bike_number_outward_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_bike_number_return',
            name='company_outward',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transactions.outward'),
            preserve_default=False,
        ),
    ]
