# Generated by Django 3.0.8 on 2022-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0022_distributor_bike_number_return_company_outward'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor_outward',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='distributor_return',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
