# Generated by Django 3.0.8 on 2022-04-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bike_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chasis_no', models.CharField(max_length=120, unique=True)),
                ('motor_no', models.CharField(max_length=120, unique=True)),
                ('controller_no', models.CharField(max_length=120, unique=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Color')),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bike', models.IntegerField()),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Color')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.variant')),
            ],
        ),
        migrations.CreateModel(
            name='outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bike_qty', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdf', to='stores.distributor')),
                ('showroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcvcxxzcv', to='stores.showroom')),
            ],
        ),
        migrations.CreateModel(
            name='inward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_qty', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.variant')),
            ],
        ),
        migrations.CreateModel(
            name='bike_number_outward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_number', models.CharField(max_length=225)),
                ('bike_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.bike_number', unique=True)),
                ('outward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.outward')),
            ],
        ),
        migrations.AddField(
            model_name='bike_number',
            name='inward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.inward'),
        ),
        migrations.CreateModel(
            name='bike_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsd', to='transactions.inward')),
            ],
        ),
    ]
