# Generated by Django 3.0.8 on 2022-05-24 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20220401_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike_number_outward',
            name='outward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outward_related', to='transactions.outward'),
        ),
    ]
