# Generated by Django 3.0.8 on 2022-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20220525_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_number_outward',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
