# Generated by Django 3.0.8 on 2022-07-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_remove_bike_number_outward_return_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='outward',
            name='bill_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
