# Generated by Django 3.0.8 on 2022-07-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_outward_bill_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outward',
            name='bill_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
