# Generated by Django 3.0.8 on 2022-07-06 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_inward_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inward',
            name='color',
        ),
    ]
