# Generated by Django 3.0.8 on 2022-07-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_stock_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike_number',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
