# Generated by Django 3.0.8 on 2022-07-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_bike_number_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_csv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_data', models.FileField(upload_to='static/')),
            ],
        ),
    ]
