# Generated by Django 3.0.8 on 2022-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20220709_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_csv',
            name='file_data',
            field=models.FileField(upload_to='static/'),
        ),
    ]
