# Generated by Django 3.0.8 on 2022-04-01 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('taluka', models.CharField(blank=True, max_length=120, null=True)),
                ('district', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('hsn_sac', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='showroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('taluka', models.CharField(blank=True, max_length=120, null=True)),
                ('district', models.CharField(blank=True, max_length=120, null=True)),
                ('mobile_number', models.IntegerField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('deactive', 'Deactive')], default='active', max_length=50, null=True)),
                ('Distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sdsd', to='stores.distributor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_price', models.IntegerField()),
                ('dealer_price', models.IntegerField()),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdsdsdcxdsx', to='stores.variant')),
            ],
        ),
    ]
