# Generated by Django 3.0.8 on 2022-04-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20220402_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='taluka',
            field=models.CharField(default='default address', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showroom',
            name='address',
            field=models.CharField(default='default address', max_length=120),
            preserve_default=False,
        ),
    ]
