# Generated by Django 3.0.8 on 2022-04-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20220403_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='GSTIN_no',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showroom',
            name='GSTIN_no',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
